[package]
name = "keysmith"
version = "0.1.0"
edition = "2021"
description = "Password, passphrase, and hash generator"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
sha2 = "0.10"
blake3 = "1"
argon2 = "0.5"
password-hash = { version = "0.5", features = ["rand_core"] }
rpassword = "7"
cybercore = "0.4"
